In [2]:
import pandas as pd
import numpy as np

In [4]:
data = np.loadtxt('asset.csv',delimiter = ',', dtype = 'str')

In [8]:
frame = pd.DataFrame({'sex':data[:,0],
             'familu_num':data[:,1],
             'captain_age':data[:,2],
             'asset':data[:,3],
             'debt':data[:,4]})

In [11]:
frame['new'] = np.arange(18640)

In [13]:
del frame.new # 안됨

In [15]:
del frame['new'] # 됨

In [16]:
frame

sex familu_num captain_age   asset    debt
0      G1          1         100       5       0
1      G1          1          21     538       0
2      G1          1          22    6000       0
3      G1          1          23      10       0
4      G1          1          23    1030       0
5      G1          1          23   10500       0
6      G1          1          23    1420       0
7      G1          1          23    4380    1000
8      G1          1          23     520       0
9      G1          1          23     909       0
10     G1          1          24    1000       0
11     G1          1          24   12830       0
12     G1          1          24    1419       0
13     G1          1          24     244       0
14     G1          1          24     250       0
15     G1          1          24    2550     700
16     G1          1          24    3820       0
17     G1          1          24     400     200
18     G1          1          24    5390      30
19     G1          1          24    6131       0
20     G1          1          24     800       0
21     G1          1          25    1000       0
22     G1          1          25    1050       0
23     G1          1          25   10700       0
24     G1          1          25    1200       0
25     G1          1          25    1220       0
26     G1          1          25   12550    5000
27     G1          1          25    2000    1700
28     G1          1          25   21290       0
29     G1          1          25    2270       0
...    ..        ...         ...     ...     ...
18610  G2          6          71   31890       0
18611  G2          6          71   37941    3000
18612  G2          6          72   10710    7000
18613  G2          6          73  112746     700
18614  G2          6          73   32212       0
18615  G2          6          75   46793       0
18616  G2          7          41    8599     920
18617  G2          7          42   34246    7000
18618  G2          7          44   94940   21400
18619  G2          7          45   64646   11000
18620  G2          7          46   21030       0
18621  G2          7          47   27596    9836
18622  G2          7          48    6043    8860
18623  G2          7          49   88517   35000
18624  G2          7          51   26411       0
18625  G2          7          52   72719   26000
18626  G2          7          53   57456   22680
18627  G2          7          56   22454       0
18628  G2          7          56  589440  227000
18629  G2          7          57   21184    7620
18630  G2          7          57   23842   12200
18631  G2          7          57    8946       0
18632  G2          7          60  129190   72000
18633  G2          7          65  166110       0
18634  G2          7          68   26045    5500
18635  G2          7          70   18631    1300
18636  G2          8          38   78746       0
18637  G2          8          61  241908    8800
18638  G2          8          70   57341   16800
18639  G2          9          51    1340       0

[18640 rows x 5 columns]

In [17]:
arr = np.ones((3,3))

In [18]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
arr[2].shape

(3,)

In [22]:
pdata = {'sex':frame['sex'][:10000],
        'asset':frame['asset']}

In [26]:
pdata = pd.DataFrame(pdata)

In [27]:
pdata.values

array([['G1', '5'],
       ['G1', '538'],
       ['G1', '6000'],
       ...,
       [nan, '241908'],
       [nan, '57341'],
       [nan, '1340']], dtype=object)

In [29]:
obj = pd.Series(range(3),index=['a','b','c'])

In [31]:
index = obj.index

In [32]:
index

Index(['a', 'b', 'c'], dtype='object')

In [34]:
index[0:]

Index(['a', 'b', 'c'], dtype='object')

In [36]:
obj.index = [1,2,3]

In [37]:
obj

1    0
2    1
3    2
dtype: int64

In [38]:
np.arange(3).shape

(3,)

In [40]:
frame.columns

Index(['sex', 'familu_num', 'captain_age', 'asset', 'debt'], dtype='object')

In [41]:
'sex' in frame

True

In [43]:
10000 in frame.index

True

In [44]:
obj = pd.Series([4,5,6,7,8],index=[4,5,6,7,8])

In [45]:
obj2 = obj.reindex([8,7,6,5,4])

In [46]:
obj2

8    8
7    7
6    6
5    5
4    4
dtype: int64

In [48]:
frame.reindex(columns=['sex','asset','debt'])

sex   asset    debt
0      G1       5       0
1      G1     538       0
2      G1    6000       0
3      G1      10       0
4      G1    1030       0
5      G1   10500       0
6      G1    1420       0
7      G1    4380    1000
8      G1     520       0
9      G1     909       0
10     G1    1000       0
11     G1   12830       0
12     G1    1419       0
13     G1     244       0
14     G1     250       0
15     G1    2550     700
16     G1    3820       0
17     G1     400     200
18     G1    5390      30
19     G1    6131       0
20     G1     800       0
21     G1    1000       0
22     G1    1050       0
23     G1   10700       0
24     G1    1200       0
25     G1    1220       0
26     G1   12550    5000
27     G1    2000    1700
28     G1   21290       0
29     G1    2270       0
...    ..     ...     ...
18610  G2   31890       0
18611  G2   37941    3000
18612  G2   10710    7000
18613  G2  112746     700
18614  G2   32212       0
18615  G2   46793       0
18616  G2    8599     920
18617  G2   34246    7000
18618  G2   94940   21400
18619  G2   64646   11000
18620  G2   21030       0
18621  G2   27596    9836
18622  G2    6043    8860
18623  G2   88517   35000
18624  G2   26411       0
18625  G2   72719   26000
18626  G2   57456   22680
18627  G2   22454       0
18628  G2  589440  227000
18629  G2   21184    7620
18630  G2   23842   12200
18631  G2    8946       0
18632  G2  129190   72000
18633  G2  166110       0
18634  G2   26045    5500
18635  G2   18631    1300
18636  G2   78746       0
18637  G2  241908    8800
18638  G2   57341   16800
18639  G2    1340       0

[18640 rows x 3 columns]

In [61]:
obj3 = pd.Series(['blue','purple','yellow'],index = [0,2,7])

In [64]:
obj4 = obj3.reindex(range(10), fill_value='black')

In [65]:
obj4

0      blue
1     black
2    purple
3     black
4     black
5     black
6     black
7    yellow
8     black
9     black
dtype: object

In [66]:
df = pd.DataFrame({"A":[1, 5, 3, 4, 2], 
                   "B":[3, 2, 4, 3, 4], 
                   "C":[2, 2, 7, 3, 4], 
                   "D":[4, 3, 6, 12, 7]}, 
                   index =["first", "second", "third", "fourth", "fifth"])

In [68]:
df.reindex(["first", "dues", "trois", "fourth", "fifth"], fill_value = 100) 

A    B    C    D
first     1    3    2    4
dues    100  100  100  100
trois   100  100  100  100
fourth    4    3    3   12
fifth     2    4    4    7

In [69]:
df.reindex(columns =["A", "B", "D", "E"], fill_value = 25)

A  B   D   E
first   1  3   4  25
second  5  2   3  25
third   3  4   6  25
fourth  4  3  12  25
fifth   2  4   7  25

In [71]:
df.reindex(columns =["A", "B", "D", "E"], fill_value = 25,inplace = true)

NameError: name 'true' is not defined

In [72]:
df

A  B  C   D
first   1  3  2   4
second  5  2  2   3
third   3  4  7   6
fourth  4  3  3  12
fifth   2  4  4   7

In [75]:
df.drop(columns = 'D',inplace=True)

In [76]:
df

A  B  C
first   1  3  2
second  5  2  2
third   3  4  7
fourth  4  3  3
fifth   2  4  4

In [78]:
re = pd.Series(['white','black','blue'],index = [0,3,7])

In [79]:
re.reindex(range(10), method = 'bfill')

0    white
1    black
2    black
3    black
4     blue
5     blue
6     blue
7     blue
8      NaN
9      NaN
dtype: object

In [81]:
re.reindex(range(10), method = 'bfill', limit = 1)

0    white
1      NaN
2    black
3    black
4      NaN
5      NaN
6     blue
7     blue
8      NaN
9      NaN
dtype: object

In [92]:
test = re.reindex([0,3,7], copy=True)

In [93]:
test2 = re.reindex([0,3,7],copy = False)

In [94]:
test

0    white
3    black
7     blue
dtype: object

In [95]:
test2

0    white
3    black
7     blue
dtype: object

In [98]:
test.drop(index=0, inplace=True)

In [99]:
test

3    black
7     blue
dtype: object

In [100]:
re

0    white
3    black
7     blue
dtype: object

In [101]:
test2.drop(index=0,inplace=True)

In [102]:
test2

3    black
7     blue
dtype: object

In [103]:
re

0    white
3    black
7     blue
dtype: object

In [104]:
re

0    white
3    black
7     blue
dtype: object

In [107]:
test = re.reindex([0,3,7], copy = True)

In [108]:
test2 = re.reindex([0,3,7],copy = False)

In [110]:
test2

0    white
3    black
7     blue
dtype: object

In [111]:
test.drop(0,inplace=True)

In [112]:
test

3    black
7     blue
dtype: object

In [113]:
re

0    white
3    black
7     blue
dtype: object

In [116]:
test2.drop(0,inplace=True)

In [117]:
test2

3    black
7     blue
dtype: object

In [119]:
re

0    white
3    black
7     blue
dtype: object

In [125]:
frame = pd.DataFrame({'Ohoi':[0,1,2,3],
             'Colorado':[4,5,6,7],
             'Utah':[8,9,10,11],
             'NewYork':[12,13,14,15]},index=['one','two','three','four'])

In [136]:
frame['one':'four']

Ohoi  Colorado  Utah  NewYork
one       0         4     8       12
two       1         5     9       13
three     2         6    10       14
four      3         7    11       15

In [137]:
frame[0:3]

Ohoi  Colorado  Utah  NewYork
one       0         4     8       12
two       1         5     9       13
three     2         6    10       14

In [143]:
frame['one']

KeyError: 'one'

In [144]:
frame

Ohoi  Colorado  Utah  NewYork
one       0         4     8       12
two       1         5     9       13
three     2         6    10       14
four      3         7    11       15

In [147]:
frame['Ohoi']

one      0
two      1
three    2
four     3
Name: Ohoi, dtype: int64

In [148]:
frame[:2]

Ohoi  Colorado  Utah  NewYork
one     0         4     8       12
two     1         5     9       13

In [154]:
frame[frame['Colorado']>5]

Ohoi  Colorado  Utah  NewYork
three     2         6    10       14
four      3         7    11       15

In [153]:
frame

Ohoi  Colorado  Utah  NewYork
one       0         4     8       12
two       1         5     9       13
three     2         6    10       14
four      3         7    11       15

In [155]:
frame < 5

Ohoi  Colorado   Utah  NewYork
one    True      True  False    False
two    True     False  False    False
three  True     False  False    False
four   True     False  False    False

In [157]:
frame.loc['one','Ohoi']

0

In [159]:
frame.iloc[0,0]

0

In [163]:
frame['Ohoi']

one      0
two      1
three    2
four     3
Name: Ohoi, dtype: int64

In [171]:
frame.at['one','Utah']

8

In [177]:
frame[0,2]

KeyError: (0, 2)

In [186]:
frame.get_value('one','Ohoi')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """Entry point for launching an IPython kernel.


0

In [191]:
ser2 = pd.Series(np.arange(3.),index=['a1','a2','a3'])

In [192]:
ser2[-1]

2.0

In [194]:
ser2[:-2]

a1    0.0
dtype: float64

In [195]:
df1 = pd.DataFrame({'a':[0.0,4.0,8.0],
             'b':[1.0,6.0,9.0],
             'c':[2.0,6.0,10.0],
             'd':[3.0,7.0,11.0]})

In [196]:
df2 = pd.DataFrame({'a':[0.0,5.0,10.0,15.0],
                   'b':[1.0,6.0,11.0,16.0],
                   'c':[2.0,7.0,12.0,17.0],
                   'd':[3.0,8.0,13.0,18.0],
                   'e':[4.0,9.0,14.0,19.0]})

In [197]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  6.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [198]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [200]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  12.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [201]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.166667  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [202]:
a = np.array([[[3,9,1],
              [5,10,-6]],
              [[12,-8,-9],
              [10,-11,12]]])

In [203]:
np.sort(a)

array([[[  1,   3,   9],
        [ -6,   5,  10]],

       [[ -9,  -8,  12],
        [-11,  10,  12]]])

In [204]:
np.sort(a,2)

array([[[  1,   3,   9],
        [ -6,   5,  10]],

       [[ -9,  -8,  12],
        [-11,  10,  12]]])

In [209]:
a.sort(0)

In [211]:
a

array([[[-11,  -8,   9],
        [ -9,   5,  10]],

       [[ -6,   3,  12],
        [  1,  10,  12]]])

In [214]:
np.cumsum(a)

array([-11, -19, -10, -19, -14,  -4, -10,  -7,   5,   6,  16,  28],
      dtype=int32)

In [219]:
pd.DataFrame(np.arange(12).reshape(4,3),columns = list('abc'))

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [222]:
df = pd.DataFrame({'b':[0.0,3.0,6.0,9.0],
                  'd':[1.0,4.0,7.0,10.0],
                  'e':[2.0,5.0,8.0,11.0]},index = ['Utah','Ohio','Texas','Oregon'])

In [223]:
df

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [231]:
ser = pd.Series(range(3),index = list('bef'))

In [232]:
ser

b    0
e    1
f    2
dtype: int64

df.sub(ser)

In [235]:
ser = df['b']

In [241]:
df.sub(ser,axis=0)

b    d    e
Utah    0.0  1.0  2.0
Ohio    0.0  1.0  2.0
Texas   0.0  1.0  2.0
Oregon  0.0  1.0  2.0

In [242]:
df

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [243]:
f = lambda x:x.max() - x.min()

In [244]:
df.apply(f)

b    9.0
d    9.0
e    9.0
dtype: float64

In [245]:
df.apply(f,axis=1)

Utah      2.0
Ohio      2.0
Texas     2.0
Oregon    2.0
dtype: float64

In [246]:
df

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [251]:
df.sort_index(axis=0,ascending=False)

b     d     e
Utah    0.0   1.0   2.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
Ohio    3.0   4.0   5.0

In [248]:
df

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [252]:
df.sort_index()

b     d     e
Ohio    3.0   4.0   5.0
Oregon  9.0  10.0  11.0
Texas   6.0   7.0   8.0
Utah    0.0   1.0   2.0

In [253]:
df.sort_index(1)

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [256]:
df = pd.DataFrame(np.arange(8).reshape(2,4),columns=['d','a','b','c'],index=['three','one'])

In [257]:
df

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [259]:
df.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [270]:
df

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [269]:
df.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [266]:
df.sort_column()

AttributeError: 'DataFrame' object has no attribute 'sort_column'

In [271]:
ser1 = pd.Series(np.arange(4))

In [272]:
ser2 = pd.Series(np.arange(4,0,-1))

In [285]:
frame = pd.DataFrame({'a':np.arange(4),
                     'b':np.arange(4,0,-1),
                     'c':np.array([0,-5,5,3])})

In [286]:
frame

a  b  c
0  0  4  0
1  1  3 -5
2  2  2  5
3  3  1  3

In [289]:
frame.sort_values(by = ['c','b'])

a  b  c
1  1  3 -5
0  0  4  0
3  3  1  3
2  2  2  5

In [290]:
frame.sort_values(by = ['c','b','a'])

a  b  c
1  1  3 -5
0  0  4  0
3  3  1  3
2  2  2  5

In [295]:
frame.sort_values(by = [1])

KeyError: 1

In [296]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [297]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [298]:
obj.rank(method='min')

0    6.0
1    1.0
2    6.0
3    4.0
4    3.0
5    2.0
6    4.0
dtype: float64

In [303]:
data = pd.Series(np.random.randn(9),index = [['a','a','a','b','b','c','c','d','d'],
                [1,2,3,1,3,1,2,2,4]])

In [304]:
data

a  1    1.177419
   2   -0.643070
   3   -0.391064
b  1   -0.481079
   3   -1.055654
c  1    0.594132
   2    0.110505
d  2    0.841065
   4   -0.317340
dtype: float64

In [305]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3, 4]],
           labels=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 3]])

In [309]:
data

a  1    1.177419
   2   -0.643070
   3   -0.391064
b  1   -0.481079
   3   -1.055654
c  1    0.594132
   2    0.110505
d  2    0.841065
   4   -0.317340
dtype: float64

In [313]:
data.unstack().stack()

a  1    1.177419
   2   -0.643070
   3   -0.391064
b  1   -0.481079
   3   -1.055654
c  1    0.594132
   2    0.110505
d  2    0.841065
   4   -0.317340
dtype: float64

In [315]:
frame.stack()

0  a    0
   b    4
   c    0
1  a    1
   b    3
   c   -5
2  a    2
   b    2
   c    5
3  a    3
   b    1
   c    3
dtype: int32

In [316]:
data.loc[:,:2]

a  1    1.177419
   2   -0.643070
b  1   -0.481079
c  1    0.594132
   2    0.110505
d  2    0.841065
dtype: float64

In [317]:
frame = pd.DataFrame(np.arange(12).reshape(4,3),
                     index = [['a','a','b','b'],[1,2,1,2]],
                    columns=[['Ohio','Ohio','Colorado'],['Green','Red','Green']])

In [318]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [323]:
swap = frame.swaplevel(0,1)

In [325]:
swap.sort_index(level=1)

Ohio     Colorado
    Green Red    Green
1 a     0   1        2
2 a     3   4        5
1 b     6   7        8
2 b     9  10       11

In [326]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [329]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1), 
                               'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'], 
                               'd': [0, 1, 2, 0, 1, 2, 3]})

In [330]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [331]:
frame.set_index(['c','d'])

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [333]:
frame.set_index(['c','d']).reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [334]:
frame.set_index(['c','d'],drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [335]:
df1 = pd.DataFrame({'key':['a','a','a','b','b','c','c','c'],
                   'data1':np.arange(8)})

In [336]:
df1

key  data1
0   a      0
1   a      1
2   a      2
3   b      3
4   b      4
5   c      5
6   c      6
7   c      7

In [337]:
df2 = pd.DataFrame({'key':['b','b','c','c','d'],
                   'data2':[10,10,-10,-10,20]})

In [338]:
df2

key  data2
0   b     10
1   b     10
2   c    -10
3   c    -10
4   d     20

In [339]:
pd.merge(df1,df2)

key  data1  data2
0   b      3     10
1   b      3     10
2   b      4     10
3   b      4     10
4   c      5    -10
5   c      5    -10
6   c      6    -10
7   c      6    -10
8   c      7    -10
9   c      7    -10

In [340]:
pd.merge(df1,df2,how='inner')

key  data1  data2
0   b      3     10
1   b      3     10
2   b      4     10
3   b      4     10
4   c      5    -10
5   c      5    -10
6   c      6    -10
7   c      6    -10
8   c      7    -10
9   c      7    -10

In [341]:
pd.merge(df1,df2,how='outer')

key  data1  data2
0    a    0.0    NaN
1    a    1.0    NaN
2    a    2.0    NaN
3    b    3.0   10.0
4    b    3.0   10.0
5    b    4.0   10.0
6    b    4.0   10.0
7    c    5.0  -10.0
8    c    5.0  -10.0
9    c    6.0  -10.0
10   c    6.0  -10.0
11   c    7.0  -10.0
12   c    7.0  -10.0
13   d    NaN   20.0

In [342]:
pd.merge(df1,df2,how='left')

key  data1  data2
0    a      0    NaN
1    a      1    NaN
2    a      2    NaN
3    b      3   10.0
4    b      3   10.0
5    b      4   10.0
6    b      4   10.0
7    c      5  -10.0
8    c      5  -10.0
9    c      6  -10.0
10   c      6  -10.0
11   c      7  -10.0
12   c      7  -10.0

In [344]:
lefth = pd.DataFrame({
'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 
                    'key2': [2000, 2001, 2002, 2001, 2002], 
'data': np.arange(5.)})


In [345]:
lefth

key1  key2  data
0    Ohio  2000   0.0
1    Ohio  2001   1.0
2    Ohio  2002   2.0
3  Nevada  2001   3.0
4  Nevada  2002   4.0

In [346]:
righth = pd.DataFrame(np.arange(12).reshape((6, 2)), 
                    index=[['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],
                                   [2001, 2000, 2000, 2000, 2001, 2002]], 
					columns=['event1', 'event2'])


In [347]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [348]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000   0.0       4       5
0    Ohio  2000   0.0       6       7
1    Ohio  2001   1.0       8       9
2    Ohio  2002   2.0      10      11
3  Nevada  2001   3.0       0       1

In [349]:
df = pd.DataFrame({'key':['foo','bar','baz'],
                  'A':[1,2,3],
                  'B':[4,5,6],
                  'C':[7,8,9]})

In [350]:
df

key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [353]:
pd.melt(df,value_vars = ['key','B','C'])

variable value
0      key   foo
1      key   bar
2      key   baz
3        B     4
4        B     5
5        B     6
6        C     7
7        C     8
8        C     9

In [354]:
np.copysign([1,1,1,1],[1,0,-1,0])

array([ 1.,  1., -1.,  1.])

In [355]:
obj = pd.Series(range(4))

In [356]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [357]:
onj2 = pd.Series(range(4))

In [364]:
pd.DataFrame(obj,columns = ['a']).add(pd.DataFrame(onj2,columns=['b']),add_value=0)

TypeError: f() got an unexpected keyword argument 'add_value'

In [367]:
df = pd.DataFrame({'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],
                  'year':[2000,2001,2002,2001,2002],
                  'pop':[1.5,1.7,3.6,2.4,2.9]}, columns = ['year','state','pop'])

In [371]:
df.columns = ['year','state','pop']

In [372]:
df

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [385]:
frame = pd.DataFrame(df,columns=['year','state','pop','debt'],index= np.arange(6))

In [386]:
frame

year   state  pop  debt
0  2000.0    Ohio  1.5   NaN
1  2001.0    Ohio  1.7   NaN
2  2002.0    Ohio  3.6   NaN
3  2001.0  Nevada  2.4   NaN
4  2002.0  Nevada  2.9   NaN
5     NaN     NaN  NaN   NaN

In [387]:
frame['year']

0    2000.0
1    2001.0
2    2002.0
3    2001.0
4    2002.0
5       NaN
Name: year, dtype: float64

In [389]:
frame.index

Int64Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [391]:
frame.loc[3]

year       2001
state    Nevada
pop         2.4
debt        NaN
Name: 3, dtype: object

In [393]:
frame['debt'] = np.arange(6)

In [394]:
frame

year   state  pop  debt
0  2000.0    Ohio  1.5     0
1  2001.0    Ohio  1.7     1
2  2002.0    Ohio  3.6     2
3  2001.0  Nevada  2.4     3
4  2002.0  Nevada  2.9     4
5     NaN     NaN  NaN     5

In [399]:
frame.iloc[:6,:0] = ''

In [405]:
frame

year  state  pop  debt   new
0   1.0      1  1.5     0  True
1   1.0      1  1.7     1  True
2   1.0      1  3.6     2  True
3   1.0      1  2.4     3  True
4   1.0      1  2.9     4  True
5   1.0      1  NaN     5  True

In [414]:
frame['new'] = (frame.debt == 0)

In [415]:
frame

year  state  pop  debt    new
0   1.0      1  1.5     0   True
1   1.0      1  1.7     1  False
2   1.0      1  3.6     2  False
3   1.0      1  2.4     3  False
4   1.0      1  2.9     4  False
5   1.0      1  NaN     5  False

In [420]:
frame['new2'] = (frame.debt == 0)

In [421]:
frame

year  state  pop  debt    new   new2
0   1.0      1  1.5     0   True   True
1   1.0      1  1.7     1  False  False
2   1.0      1  3.6     2  False  False
3   1.0      1  2.4     3  False  False
4   1.0      1  2.9     4  False  False
5   1.0      1  NaN     5  False  False

In [423]:
del frame['new2']

In [424]:
frame

year  state  pop  debt    new
0   1.0      1  1.5     0   True
1   1.0      1  1.7     1  False
2   1.0      1  3.6     2  False
3   1.0      1  2.4     3  False
4   1.0      1  2.9     4  False
5   1.0      1  NaN     5  False

In [425]:
frame.loc[:,2]

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [2] of <class 'int'>

In [426]:
ser = pd.Series(np.random.randn(3),index = list('acd'))

In [427]:
ser

a    1.303692
c   -1.145841
d    0.271938
dtype: float64

In [433]:
data = pd.Series(np.random.randn(9),
                index = [['a','a','a','b','b','c','c','d','d'],
                        [1,2,3,1,3,1,2,2,3]])

In [434]:
data

a  1    0.269428
   2   -1.624537
   3    1.759427
b  1    1.730270
   3   -0.139758
c  1   -0.588422
   2   -0.168728
d  2    0.208882
   3    0.188693
dtype: float64

In [435]:
data.iloc[0]

0.26942766489727965

In [436]:
data.iloc[1]

-1.6245371897274699

In [437]:
obj = pd.Series(np.arange(10))

In [438]:
obj

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [441]:
obj.drop(4,inplace=True)

In [442]:
obj

0    0
1    1
2    2
3    3
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [443]:
frame

year  state  pop  debt    new
0   1.0      1  1.5     0   True
1   1.0      1  1.7     1  False
2   1.0      1  3.6     2  False
3   1.0      1  2.4     3  False
4   1.0      1  2.9     4  False
5   1.0      1  NaN     5  False

In [445]:
del frame['new']

In [449]:
frame.drop(2,inplace=True)

In [452]:
frame.drop('pop',axis=1,inplace=True)

In [453]:
frame

year  state  debt
0   1.0      1     0
1   1.0      1     1
3   1.0      1     3
4   1.0      1     4
5   1.0      1     5

In [459]:
frame[['year','state']]

year  state
0   1.0      1
1   1.0      1
3   1.0      1
4   1.0      1
5   1.0      1

In [460]:
frame[:2]

year  state  debt
0   1.0      1     0
1   1.0      1     1

In [468]:
frame[frame['debt'] > 1]

year  state  debt
3   1.0      1     3
4   1.0      1     4
5   1.0      1     5

In [470]:
frame == 1 

year  state   debt
0  True   True  False
1  True   True   True
3  True   True  False
4  True   True  False
5  True   True  False

In [473]:
df = pd.DataFrame({'b':[0,3,6,9],
                  'd':[1,4,7,10],
                  'e':[2,5,8,11]}, index = ['Utah','Ohio','Texas','Oregon'])

In [474]:
df

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [475]:
ser2 = pd.Series(range(3), index=['b','e','f'])

In [476]:
ser2

b    0
e    1
f    2
dtype: int64

In [477]:
df - ser2

b   d     e   f
Utah    0.0 NaN   1.0 NaN
Ohio    3.0 NaN   4.0 NaN
Texas   6.0 NaN   7.0 NaN
Oregon  9.0 NaN  10.0 NaN

In [479]:
df.sub(ser2,axis=0)

b   d   e
Ohio   NaN NaN NaN
Oregon NaN NaN NaN
Texas  NaN NaN NaN
Utah   NaN NaN NaN
b      NaN NaN NaN
e      NaN NaN NaN
f      NaN NaN NaN