In [1]:
1 + 2

3

In [2]:
(1 + 2 * 3 - 4) / 5

0.6

In [3]:
2 ** 8

256

In [4]:
a=1.5

In [5]:
a="learning"

In [6]:
b='abc'

In [7]:
type(100)

int

In [8]:
type(100.1)

float

In [9]:
a=(1, 2, 3)

In [10]:
 b=(2,)

In [11]:
False

False

In [12]:
b=(2,)
b[0]+1

3

In [13]:
x = 1 / 3
x
y = 2 / 3
y

0.6666666666666666

In [14]:
x = 1 / 3
print(x)
y = 2 / 3
print(y)
print('x= ' + str(x))
print('weight = {0} kg'.format(x))

0.3333333333333333
0.6666666666666666
x= 0.3333333333333333
weight = 0.3333333333333333 kg


In [15]:
x = 1 / 3
y = 1 / 7
z = 1 / 4
print ('weight : {0} kg {1} kg {2} kg'.format(x, y, z))

weight : 0.3333333333333333 kg 0.14285714285714285 kg 0.25 kg


In [16]:
print('weight: {0:.2f} kg, y={1:.2f} kg, z={2:.2f} kg'.format(x,y,z))

weight: 0.33 kg, y=0.14 kg, z=0.25 kg


In [17]:
x = [1, 1, 2, 3, 5] # list의 정의
print(x) # 표시


[1, 1, 2, 3, 5]


In [18]:
x[0]

1

In [19]:
x[2]

2

In [20]:
print(type(x))
print(type(x[0]))


<class 'list'>
<class 'int'>


In [21]:
s=['SUN', 1, 'MON', 2]
print(type(s[0]))
print(type(s[1]))


<class 'str'>
<class 'int'>


In [22]:
a=[[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [23]:
a=[[1, 2, 3], [4, 5, 6]]
print(a[0][1])

2


In [24]:
x=[1, 1, 2, 3, 5]
x[3] = 100
print(x)

[1, 1, 2, 100, 5]


In [25]:
x=[1, 1, 2, 3, 5]
len(x)

5

In [26]:
y = range(5, 10)
print(y[0], y[1], y[2], y[3], y[4])


5 6 7 8 9


In [27]:
print(y)

range(5, 10)


In [28]:
z=list(range(5, 10))
print(z)


[5, 6, 7, 8, 9]


In [29]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
a=(1, 2, 3)
print(a)


(1, 2, 3)


In [31]:
a[1]

2

In [32]:
type(a)

tuple

In [33]:
a = (1)
type(a)
    

int

In [34]:
a = (1,)
type(a)


tuple

In [35]:
x = 11
if x > 10:
    print('x is ') # ... (A1)
    print('        larger than 10.') # ... (A2)
else:
    print('x is smaller than 11') # ... (B1) 


x is 
        larger than 10.


In [36]:
x > 10

True

In [37]:
type(x > 10)

bool

In [38]:
x = 15
if 10 <= x and x <= 20:
    print('x is between 10 and 20.')


x is between 10 and 20.


In [39]:
for i in [1, 2, 3]:
    print(i)


1
2
3


In [40]:
num = [2, 4, 6, 8, 10]
for i in range(len(num)):
    num[i] = num[i] * 2
print(num)


[4, 8, 12, 16, 20]


In [41]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [42]:
import numpy as np

In [43]:
x=np.array([1, 2, 3])
x

array([1, 2, 3])

In [44]:
print(x)

[1 2 3]


In [45]:
y=np.array([4, 5, 6])
print(x + y)

[5 7 9]


In [46]:
type(x)

numpy.ndarray

In [47]:
x[0]

1

In [48]:
x[0] = 100
print(x)

[100   2   3]


In [49]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [50]:
print(np.arange(5, 10))

[5 6 7 8 9]


In [51]:
j=np.array([4, 5, 6])
for i in np.arange(1,4):
    print(i)
    print(i + j)

1
[5 6 7]
2
[6 7 8]
3
[7 8 9]


In [52]:
a = np.array([1, 1])
b = a
print('a =' + str(a))
print('b =' + str(b))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))

a =[1 1]
b =[1 1]
b =[100   1]
a =[100   1]


In [53]:
a = np.array([1, 1])
b = a.copy()
print('a =' + str(a))
print('b =' + str(b))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))


a =[1 1]
b =[1 1]
b =[100   1]
a =[1 1]


In [54]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)


[[1 2 3]
 [4 5 6]]


In [55]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.shape

(2, 3)

In [56]:
w, h = x.shape
print(w)
print(h)

2
3


In [57]:
type(x.shape)

tuple

In [58]:
w, h = x.shape
print(w)
print(h)


2
3


In [59]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2]


6

In [60]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[0, 2]

3

In [61]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


In [62]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [63]:
print(np.zeros((2, 10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [64]:
print(np.ones((2, 10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [65]:
np.random.rand(2, 3)

array([[0.52963493, 0.75531414, 0.20122359],
       [0.1105525 , 0.21340821, 0.54154738]])

In [66]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [67]:
a.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


In [69]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(10 * x)

[[40 40 40]
 [80 80 80]]


In [70]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(np.exp(x))

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


In [71]:
v = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([[1, 1], [2, 2], [3, 3]])
print(v.dot(w))

[[14 14]
 [32 32]]


In [72]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [73]:
print(x[5:])

[5 6 7 8 9]


In [74]:
print(x[3:8])

[3 4 5 6 7]


In [75]:
print(x[3:8:2])

[3 5 7]


In [76]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [77]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y)
print(y[:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


In [78]:
x = np.array([1, 1, 2, 3, 5, 8, 13])
x > 3

array([False, False, False, False,  True,  True,  True])

In [79]:
x[x > 3]

array([ 5,  8, 13])

In [80]:
x[x > 3] = 999
print(x)

[  1   1   2   3 999 999 999]


In [81]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [82]:
np.random.randint(5)

0

In [83]:
np.random.randint(5, 10, (3, 2))

array([[9, 5],
       [6, 8],
       [5, 5]])

In [84]:
def my_func1():
    print('Hi!')
# 함수 my_func1()의 정의는 여기까지
my_func1() # 함수를 실행

Hi!


In [85]:
def my_func2(a, b):
    c = a + b
    return c


my_func2(1, 2)

3

In [86]:
def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m, s

In [87]:
data=np.random.randn(100)
data_mean, data_std = my_func3(data)
print('mean:{0:3.2f}, std:{1:3.2f}'.format(data_mean, data_std))

mean:0.00, std:1.06


In [88]:
output = my_func3(data)
print(output)
print(type(output))
print('mean:{0:3.2f}, std:{1:3.2f}'.format(output[0], output[1]))

(0.002269224053547081, 1.0551678713659625)
<class 'tuple'>
mean:0.00, std:1.06


In [89]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy', data)  # 세이브
data = []                      # 데이터 삭제
print(data)
data = np.load('datafile.npy') # 로드
print(data)

[ 0.28997285  0.34626757 -0.66263271 -1.07081366 -0.2590175 ]
[]
[ 0.28997285  0.34626757 -0.66263271 -1.07081366 -0.2590175 ]


In [90]:
data1 = np.array([1, 2, 3])
data2 = np.array([10, 20, 30])
np.savez('datafile2.npz', data1=data1, data2=data2) # 세이브
data1 = [] # 데이터 삭제
data2 = []
outfile = np.load('datafile2.npz') # 로드
print(outfile.files) # 저장된 데이터 표시
data1 = outfile['data1'] # data1 꺼내기
data2 = outfile['data2'] # data2 꺼내기
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]
